"""Models for SSSOM."""

from __future__ import annotations

import datetime
from collections.abc import Callable, Sequence
from typing import TYPE_CHECKING, Annotated, Literal, NamedTuple, TypeAlias

from curies.vocabulary import matching_processes
from pydantic import AnyUrl, BaseModel, ConfigDict, Field

from .constants import EntityTypeLiteral

if TYPE_CHECKING:
    import curies

__all__ = [
    "Cardinality",
    "ExpandedRecord",
    "Record",
    "RecordPredicate",
]

#: Cardinality annotations, which are valid within the scope of a mapping set
#: but should not be saved as part of a mapping
Cardinality: TypeAlias = Literal["1:1", "1:n", "n:1", "1:0", "0:1", "n:n", "0:0"]


class Record(BaseModel):
    """Represents an SSSOM record (i.e., a row in a SSSOM TSV file).

    A SSSOM record contains both the mapping set information and mapping information.
    """

    model_config = ConfigDict(frozen=True)

    record_id: str | None = None

    subject_id: str
    subject_label: str | None = None
    subject_category: str | None = None
    predicate_id: str
    predicate_label: str | None = None
    predicate_modifier: Literal["Not"] | None = None
    object_id: str
    object_label: str | None = None
    object_category: str | None = None
    mapping_justification: Annotated[str, Field(examples=[p.curie for p in matching_processes])]
    author_id: list[str] | None = None
    author_label: list[str] | None = None
    reviewer_id: list[str] | None = None
    reviewer_label: list[str] | None = None
    creator_id: list[str] | None = None
    creator_label: list[str] | None = None
    license: str | None = None
    subject_type: Annotated[
        EntityTypeLiteral | None,
        Field(description="See https://mapping-commons.github.io/sssom/subject_type"),
    ] = None
    subject_source: str | None = None
    subject_source_version: str | None = None
    object_type: Annotated[
        EntityTypeLiteral | None,
        Field(description="See https://mapping-commons.github.io/sssom/object_type"),
    ] = None
    object_source: str | None = None
    object_source_version: str | None = None
    predicate_type: Annotated[
        EntityTypeLiteral | None,
        Field(description="See https://mapping-commons.github.io/sssom/predicate_type"),
    ] = None
    mapping_provider: AnyUrl | None = None
    #: https://mapping-commons.github.io/sssom/mapping_source/
    mapping_source: str | None = None
    #: see https://mapping-commons.github.io/sssom/MappingCardinalityEnum/
    mapping_cardinality: Cardinality | None = None
    cardinality_scope: list[str] | None = None
    mapping_tool: str | None = None
    mapping_tool_id: str | None = None
    mapping_tool_version: str | None = None
    mapping_date: datetime.date | None = None
    publication_date: datetime.date | None = None
    review_date: datetime.date | None = None
    confidence: Annotated[
        float | None,
        Field(
            ge=0.0,
            le=1.0,
            description="""\
        An assessment of the confidence of the mapping, reported by the method used to generate it.

        This means that confidence values aren't generally comparable, though they should follow
        the rough standard that closer to 1 is more confident and closer to 0 is less confident.

        Most of the lexical mappings already in Biomappings were generated with Gilda.
        Depending on the script, the score therefore refers to either:

        1. The Gilda match score, inspired by https://aclanthology.org/W15-3801/. Section 5.2 of
           the `supplementary material for the Gilda paper <https://doi.org/10.1093/bioadv/vbac034>`_
           describes this score in detail, where 1.0 is best and 0 is worst.
           https://github.com/biopragmatics/biomappings/blob/master/scripts/generate_agrovoc_mappings.py
           is an example that uses this variant.
        2. A high-level estimation of the precision of the scores generated by the given script.
           For example, the CL-MeSH mappings were estimated to be 90% correct, so all the mappings
           generated by
           https://github.com/biopragmatics/biomappings/blob/master/scripts/generate_cl_mesh_mappings.py
           are marked with 0.9 as its score.

        However, other variants are possible. For example, this confidence could reflect the loss
        function if a knowledge graph embedding model was used ot generate a mapping prediction.
        """,
        ),
    ] = None
    reviewer_agreement: Annotated[
        float | None, Field(ge=-1.0, le=1.0, examples=[-1.0, 0.0, 1.0])
    ] = None
    curation_rule: list[str] | None = None
    curation_rule_text: list[str] | None = None
    subject_match_field: list[str] | None = None
    object_match_field: list[str] | None = None
    match_string: list[str] | None = None
    subject_preprocessing: list[str] | None = None
    object_preprocessing: list[str] | None = None
    similarity_score: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    similarity_measure: str | None = None
    see_also: list[str] | None = None
    issue_tracker_item: str | None = None
    other: str | None = None
    comment: str | None = None

    def expand(
        self, converter: curies.Converter, exclude: set[str] | None = None
    ) -> ExpandedRecord:
        """Expand CURIEs to URIs in the record."""
        data = self.model_dump(exclude_none=True, exclude_unset=True, exclude=exclude)
        for key in SINGLE_REFERENCE_FIELDS:
            if curie := data.get(key):
                data[key] = converter.expand(curie, strict=True)
        for key in MULTIPLE_REFERENCE_FIELDS:
            if curies_ := data.get(key):
                data[key] = [converter.expand(curie, strict=True) for curie in curies_]
        return ExpandedRecord.model_validate(data)


#: field names that contain a reference or optional reference
SINGLE_REFERENCE_FIELDS = {
    "record_id",
    "subject_id",
    "predicate_id",
    "object_id",
    "mapping_justification",
    # non-core
    "subject_source",
    "object_source",
    "subject_category",
    "object_category",
    "mapping_source",
}
#: field names that contain reference lists
MULTIPLE_REFERENCE_FIELDS = {
    "subject_match_field",
    "subject_preprocessing",
    "object_match_field",
    "object_preprocessing",
    "author_id",
    "creator_id",
    "reviewer_id",
    "curation_rule",
}

#: A predicate for a record
RecordPredicate: TypeAlias = Callable[[Record], bool]


class ExpandedRecord(BaseModel):
    """Represents an SSSOM record (i.e., a row in a SSSOM TSV file) expanded with URIs."""

    model_config = ConfigDict(frozen=True)

    record_id: AnyUrl | None = None
    subject_id: AnyUrl
    subject_label: str | None = None
    subject_category: str | None = None
    predicate_id: AnyUrl
    predicate_label: str | None = None
    predicate_modifier: Literal["Not"] | None = None
    object_id: str
    object_label: str | None = None
    object_category: str | None = None
    mapping_justification: Annotated[str, Field(examples=[p.curie for p in matching_processes])]
    author_id: list[str] | None = None
    author_label: list[str] | None = None
    reviewer_id: list[AnyUrl] | None = None
    reviewer_label: list[str] | None = None
    creator_id: list[AnyUrl] | None = None
    creator_label: list[str] | None = None
    license: str | None = None
    subject_type: Annotated[
        EntityTypeLiteral | None,
        Field(description="See https://mapping-commons.github.io/sssom/subject_type"),
    ] = None
    subject_source: AnyUrl | None = None
    subject_source_version: str | None = None
    object_type: Annotated[
        EntityTypeLiteral | None,
        Field(description="See https://mapping-commons.github.io/sssom/object_type"),
    ] = None
    object_source: AnyUrl | None = None
    object_source_version: str | None = None
    predicate_type: Annotated[
        EntityTypeLiteral | None,
        Field(description="See https://mapping-commons.github.io/sssom/predicate_type"),
    ] = None
    mapping_provider: AnyUrl | None = None
    mapping_source: AnyUrl | None = None
    #: see https://mapping-commons.github.io/sssom/MappingCardinalityEnum/
    mapping_cardinality: Cardinality | None = None
    cardinality_scope: list[str] | None = None
    mapping_tool: str | None = None
    mapping_tool_id: AnyUrl | None = None
    mapping_tool_version: str | None = None
    mapping_date: datetime.date | None = None
    publication_date: datetime.date | None = None
    review_date: datetime.date | None = None
    confidence: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    reviewer_agreement: Annotated[
        float | None, Field(ge=-1.0, le=1.0, examples=[-1.0, 0.0, 1.0])
    ] = None
    curation_rule: list[AnyUrl] | None = None
    curation_rule_text: list[str] | None = None
    subject_match_field: list[AnyUrl] | None = None
    object_match_field: list[AnyUrl] | None = None
    match_string: list[str] | None = None
    subject_preprocessing: list[AnyUrl] | None = None
    object_preprocessing: list[AnyUrl] | None = None
    similarity_score: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    similarity_measure: str | None = None
    see_also: list[str] | None = None
    issue_tracker_item: str | None = None
    other: str | None = None
    comment: str | None = None

    def compress(self, converter: curies.Converter) -> Record:
        """Compress expanded URIs into CURIEs."""
        data = self.model_dump(exclude_none=True, exclude_unset=True)
        for key in SINGLE_REFERENCE_FIELDS:
            if uri := data.get(key):
                data[key] = converter.compress(str(uri), strict=True)
        for key in MULTIPLE_REFERENCE_FIELDS:
            if uris := data.get(key):
                data[key] = [converter.compress(str(uri), strict=True) for uri in uris]
        return Record.model_validate(data)


SKIP_SLOTS = {"record_id", "mapping_cardinality"}


def expanded_record_to_str(mapping: ExpandedRecord, *, _debug: bool = False) -> str:
    """Convert a mapping to a S-expression string."""
    return box_to_str(expanded_record_to_box(mapping), _debug=_debug)


def expanded_record_to_box(record: ExpandedRecord) -> Box:
    """Convert a mapping to a S-expression."""
    boxes: list[Box] = []
    for name in ExpandedRecord.model_fields:
        if name in SKIP_SLOTS:
            continue
        match getattr(record, name, None):
            case None:
                continue
            case str() | float() | bool() | datetime.date() as value:
                boxes.append(Box(name, value))
            case AnyUrl() as url:
                boxes.append(Box(name, str(url)))
            case list() as values:
                if not values:
                    continue
                if all(isinstance(v, str) for v in values):
                    boxes.append(Box(name, values))
                elif all(isinstance(v, AnyUrl) for v in values):
                    boxes.append(Box(name, [str(v) for v in values]))
                else:
                    raise TypeError(f"invalid box value: {values}")
            case _ as value:
                raise NotImplementedError(f"not implemented for {type(value)}")
    return Box("mapping", boxes)


class Box(NamedTuple):
    """A value."""

    label: str
    value: str | float | bool | datetime.date | Sequence[str | float | bool | datetime.date | Box]


def box_to_str(box: Box, *, max_precision: int = 4, _debug: bool = False) -> str:
    """Convert a S-expression object to a string."""
    start = f"{len(box.label)}:{box.label}"
    match box.value:
        case str() | float() | bool() | datetime.date():
            return f"({start}{_fmt_primitive(box.value, max_precision=max_precision)})"
        case list():
            rr = []
            for value in box.value:
                match value:
                    case str() | float() | bool():
                        rr.append(_fmt_primitive(value, max_precision=max_precision))
                    case Box():
                        rr.append(box_to_str(value, max_precision=max_precision, _debug=_debug))
            if _debug:
                inside = "\n".join(rr)
            else:
                inside = "".join(rr)
            return f"({start}({inside}))"
        case _:
            raise TypeError(f"invalid box value: {box.value}")


def _fmt_primitive(value: str | float | bool | datetime.date, *, max_precision: int = 4) -> str:
    match value:
        case str():
            pass
        case float():
            value = str(round(value, max_precision))
        case bool():
            raise NotImplementedError
        case datetime.date():
            value = value.strftime("%Y-%m-%d")
    return f"{len(value)}:{value}"
