"""Create OWL bridges based on https://github.com/INCATools/ontology-development-kit/issues/626#issuecomment-3285032670."""

from __future__ import annotations

import datetime
from collections.abc import Iterable
from pathlib import Path
from typing import Any, TextIO

import curies
import functional_owl as f
import rdflib
from curies import Reference
from curies import vocabulary as v
from functional_owl import (
    Annotation,
    Axiom,
    ClassAssertion,
    DeclarationType,
    DifferentIndividuals,
    DisjointClasses,
    DisjointDataProperties,
    DisjointObjectProperties,
    EquivalentClasses,
    EquivalentDataProperties,
    EquivalentObjectProperties,
    LiteralBox,
    SameIndividual,
    SubAnnotationPropertyOf,
    SubClassOf,
    SubDataPropertyOf,
    SubObjectPropertyOf,
    write_ontology,
)
from functional_owl.dsl import Box

from ..api import MappingSet, SemanticMapping
from ..process import filter_by_confidence, invert_narrow_matches
from ..version import get_version

__all__ = [
    "get_owl_bridge_axiom",
    "get_owl_bridge_axioms",
    "write_owl_bridge",
]

HUMAN_URI = rdflib.URIRef("http://purl.obolibrary.org/obo/NCBITaxon_9606")


def write_owl_bridge(
    mappings: Iterable[SemanticMapping],
    path: str | Path | TextIO,
    *,
    converter: curies.Converter,
    metadata: MappingSet | None = None,
    minimum_confidence: float | None = None,
    mapping_annotations: bool = False,
    declarations: bool = False,
    **kwargs: Any,
) -> None:
    """Write OWL bridge axioms as an OWL file.

    :param mappings: semantic mappings
    :param path: path to file or a file-like object
    :param converter: a converter
    :param metadata: metadata to annotate to the "ontology"
    :param minimum_confidence: minimum confidence level to keep for exporting as a
        bridge
    :param mapping_annotations: whether to include mapping annotations
    :param declarations: whether to include declarations (and labels, if available)
    :param kwargs: keyword arguments to pass to :func:`functional_owl.write_ontology`.

    .. note::

        This function automatically inverts SKOS narrow matches
    """
    # add pav since it's part of the output model
    converter.add_prefix("pav", "http://purl.org/pav/", merge=True)
    converter.add_prefix("dcterms", "http://purl.org/dc/terms/", merge=True)

    write_ontology(
        prefixes=converter,
        axioms=list(
            get_owl_bridge_axioms(
                mappings,
                converter=converter,
                minimum_confidence=minimum_confidence,
                mapping_annotations=mapping_annotations,
                declarations=declarations,
            )
        ),
        file=path,
        annotations=_get_ontology_annotations(metadata),
        **kwargs,
    )


def _get_ontology_annotations(metadata: MappingSet | None) -> list[Annotation]:
    today = datetime.date.today().isoformat()
    rv = [
        Annotation(
            v.has_comment, LiteralBox(f"Generated by sssom-pydantic (v{get_version()}) on {today}")
        )
    ]
    if metadata is None:
        return rv
    if metadata.description:
        rv.append(Annotation(v.has_description, LiteralBox(metadata.description)))
    if metadata.title:
        rv.append(Annotation(v.has_title, LiteralBox(metadata.title)))
    if metadata.version:
        rv.append(Annotation(v.owl_version_info, LiteralBox(metadata.version)))
    if metadata.license:
        rv.append(Annotation(v.has_license, rdflib.URIRef(str(metadata.license))))
    if metadata.comment:
        rv.append(Annotation(v.has_comment, LiteralBox(metadata.comment)))
    for source_url in metadata.source or []:
        rv.append(Annotation(v.has_source, rdflib.URIRef(str(source_url))))
    for see_also_url in metadata.see_also or []:
        rv.append(Annotation(v.see_also, rdflib.URIRef(str(see_also_url))))
    for creator in metadata.creators or []:
        rv.append(Annotation(v.has_creator, creator))
    return rv


def get_owl_bridge_axioms(
    mappings: Iterable[SemanticMapping],
    *,
    converter: curies.Converter,
    minimum_confidence: float | None = None,
    mapping_annotations: bool = False,
    declarations: bool = False,
) -> Iterable[Box]:
    """Iterate over OWL bridge axioms from semantic mappings."""
    if minimum_confidence is not None:
        mappings = filter_by_confidence(mappings, minimum_confidence)
    mappings = invert_narrow_matches(mappings, converter=converter)
    authors = set()
    for m in mappings:
        if axiom := get_owl_bridge_axiom(m, mapping_annotations=mapping_annotations):
            if declarations:
                yield f.Declaration(m.subject, _type_to_declaration_type(m.subject, m.predicate))
                yield f.Declaration(m.object, _type_to_declaration_type(m.object, m.predicate))
                if m.subject.name:
                    yield f.LabelMacro(m.subject, m.subject.name)
                if m.object.name:
                    yield f.LabelMacro(m.object, m.object.name)
            if m.authors:
                authors.update(m.authors)
            yield axiom
    if mapping_annotations and authors:
        yield f.Declaration(HUMAN_URI, "Class")
        yield f.LabelMacro(HUMAN_URI, "human")
        for author in authors:
            yield f.Declaration(author, "NamedIndividual")
            yield f.ClassAssertion(HUMAN_URI, author)


DEFAULTS: dict[Reference, DeclarationType] = {
    v.exact_match: "Class",
    v.broad_match: "Class",
    v.narrow_match: "Class",
    v.equivalent_class: "Class",
    v.equivalent_property: "ObjectProperty",
    v.subproperty_of: "ObjectProperty",
    v.is_a: "Class",
    v.rdf_type: "NamedIndividual",
    v.same_as: "NamedIndividual",
}


def _type_to_declaration_type(t: Reference | None, p: Reference) -> DeclarationType:
    if t is None:
        return DEFAULTS.get(p, "Class")
    return "Class"


def get_owl_bridge_axiom(m: SemanticMapping, *, mapping_annotations: bool = False) -> Axiom | None:
    """Get an OWL bridge axiom from a semantic mapping."""
    anns = _get_axiom_annotations(m) if mapping_annotations else None
    match m.predicate, m.predicate_modifier:
        case v.exact_match, None:
            if _is_class(m.subject_type):
                return EquivalentClasses([m.subject, m.object], annotations=anns)
            elif m.subject_type == v.owl_named_individual:
                return SameIndividual([m.subject, m.object], annotations=anns)
            elif m.subject_type == v.owl_object_property:
                return EquivalentObjectProperties([m.subject, m.object], annotations=anns)
            elif m.subject_type == v.owl_data_property:
                return EquivalentDataProperties([m.subject, m.object], annotations=anns)
            # note, there's no concept of EquivalentAnnotationProperties since
            # these aren't used for logical axioms

        case v.exact_match, "Not":  # interestingly, a constant can't be used here
            if _is_class(m.subject_type):
                return DisjointClasses([m.subject, m.object], annotations=anns)
            elif m.subject_type == v.owl_named_individual:
                return DifferentIndividuals([m.subject, m.object], annotations=anns)
            elif m.subject_type == v.owl_object_property:
                return DisjointObjectProperties([m.subject, m.object], annotations=anns)
            elif m.subject_type == v.owl_data_property:
                return DisjointDataProperties([m.subject, m.object], annotations=anns)
            # note, there's no concept of DisjointAnnotationProperties since
            # these aren't used for logical axioms

        case v.broad_match, None:
            if _is_class(m.subject_type):
                return SubClassOf(m.subject, m.object, annotations=anns)
            elif m.subject_type == v.owl_named_individual and _is_class(m.object_type):
                return ClassAssertion(m.object, m.subject, annotations=anns)
            elif m.subject_type == v.owl_object_property:
                return SubObjectPropertyOf(m.subject, m.object, annotations=anns)
            elif m.subject_type == v.owl_data_property:
                return SubDataPropertyOf(m.subject, m.object, annotations=anns)
            elif m.subject_type == v.owl_annotation_property:
                return SubAnnotationPropertyOf(m.subject, m.object, annotations=anns)

        case v.is_a, None:
            return SubClassOf(m.subject, m.object, annotations=anns)
        case v.rdf_type, None:
            return ClassAssertion(m.object, m.subject, annotations=anns)
        case v.subproperty_of, None:
            if m.subject_type is None or m.subject_type == v.owl_object_property:
                return SubObjectPropertyOf(m.subject, m.object, annotations=anns)
            elif m.subject_type == v.owl_data_property:
                return SubDataPropertyOf(m.subject, m.object, annotations=anns)
            elif m.subject_type == v.owl_annotation_property:
                return SubAnnotationPropertyOf(m.subject, m.object, annotations=anns)

        case v.equivalent_class, None:
            return EquivalentClasses([m.subject, m.object], annotations=anns)
        case v.equivalent_class, "Not":
            return DisjointClasses([m.subject, m.object], annotations=anns)

        case v.same_as, None:
            return SameIndividual([m.subject, m.object], annotations=anns)
        case v.same_as, "Not":
            return DifferentIndividuals([m.subject, m.object], annotations=anns)

        case v.equivalent_property, None:
            if m.subject_type is None or m.subject_type == v.owl_object_property:
                return EquivalentObjectProperties([m.subject, m.object], annotations=anns)
            elif m.subject_type == v.owl_data_property:
                return EquivalentDataProperties([m.subject, m.object], annotations=anns)
            # note, there's no concept of EquivalentAnnotationProperties since
            # these aren't used for logical axioms
        case v.equivalent_property, "Not":
            if m.subject_type is None or m.subject_type == v.owl_object_property:
                return DisjointObjectProperties([m.subject, m.object], annotations=anns)
            elif m.subject_type == v.owl_data_property:
                return DisjointDataProperties([m.subject, m.object], annotations=anns)
            # note, there's no concept of DisjointAnnotationProperties since
            # these aren't used for logical axioms

    return None


def _is_class(r: curies.Reference | None) -> bool:
    return r is None or r == v.owl_class or r == v.skos_concept


def _get_axiom_annotations(mapping: SemanticMapping) -> list[Annotation]:
    rv = []
    for author in mapping.authors or []:
        rv.append(Annotation("pav:authoredBy", author))
    if mapping.confidence:
        rv.append(Annotation("sssom:confidence", mapping.confidence))
    return rv
