"""Create OWL bridges based on https://github.com/INCATools/ontology-development-kit/issues/626#issuecomment-3285032670.

Implemented in:

- https://github.com/cthoyt/sssom-pydantic/pull/128
- https://github.com/cthoyt/sssom-pydantic/pull/157
- https://github.com/cthoyt/sssom-pydantic/pull/158
"""

from __future__ import annotations

import datetime
import logging
from collections.abc import Iterable
from functools import partial
from pathlib import Path
from typing import Any, TextIO, TypedDict, NotRequired, TypeAlias, Literal

import curies
import functional_owl as f
import rdflib
from curies import Reference
from curies import vocabulary as v
from functional_owl import (
    Annotation,
    Axiom,
    Box,
    ClassAssertion,
    DeclarationType,
    DifferentIndividuals,
    DisjointClasses,
    AnnotationAssertion,
    DisjointDataProperties,
    DisjointObjectProperties,
    EquivalentClasses,
    EquivalentDataProperties,
    EquivalentObjectProperties,
    InverseObjectProperties,
    LiteralBox,
    SameIndividual,
    SubAnnotationPropertyOf,
    SubClassOf,
    SubDataPropertyOf,
    SubObjectPropertyOf,
    write_ontology,
)
from rdflib import XSD

from ..api import MappingSet, SemanticMapping
from ..process import filter_by_confidence, invert_narrow_matches
from ..version import get_version

__all__ = [
    "get_owl_bridge_axiom",
    "get_owl_bridge_axioms",
    "write_owl_bridge",
]

logger = logging.getLogger(__name__)

HUMAN_URI = rdflib.URIRef("http://purl.obolibrary.org/obo/NCBITaxon_9606")

Mechanism: TypeAlias = Literal["bridge", "annotation"]


def write_owl_bridge(
    mappings: Iterable[SemanticMapping],
    path: str | Path | TextIO,
    *,
    converter: curies.Converter,
    metadata: MappingSet | None = None,
    minimum_confidence: float | None = None,
    mapping_annotations: bool = False,
    declarations: bool = False,
    **kwargs: Any,
) -> None:
    """Write OWL bridge axioms as an OWL file.

    :param mappings: semantic mappings
    :param path: path to file or a file-like object
    :param converter: a converter
    :param metadata: metadata to annotate to the "ontology"
    :param minimum_confidence: minimum confidence level to keep for exporting as a
        bridge
    :param mapping_annotations: whether to include mapping annotations
    :param declarations: whether to include declarations (and labels, if available)
    :param kwargs: keyword arguments to pass to :func:`functional_owl.write_ontology`.

    .. note::

        This function automatically inverts SKOS narrow matches
    """
    # add pav since it's part of the output model
    converter.add_prefix("pav", "http://purl.org/pav/", merge=True)
    converter.add_prefix("dcterms", "http://purl.org/dc/terms/", merge=True)

    write_ontology(
        prefixes=converter,
        axioms=list(
            get_owl_bridge_axioms(
                mappings,
                converter=converter,
                minimum_confidence=minimum_confidence,
                mapping_annotations=mapping_annotations,
                declarations=declarations,
            )
        ),
        file=path,
        annotations=get_metadata_annotations(metadata, converter=converter)
        if metadata is not None
        else None,
        **kwargs,
    )


def get_metadata_annotations(metadata: MappingSet, converter: curies.Converter) -> list[Annotation]:
    """Get annotations from mapping set metadata."""
    today = datetime.date.today().isoformat()
    rv = [
        Annotation(
            v.has_comment, LiteralBox(f"Generated by sssom-pydantic (v{get_version()}) on {today}")
        )
    ]
    if metadata.description:
        rv.append(Annotation(v.has_description, LiteralBox(metadata.description)))
    if metadata.title:
        rv.append(Annotation(v.has_title, LiteralBox(metadata.title)))
    if metadata.version:
        rv.append(Annotation(v.owl_version_info, LiteralBox(metadata.version)))
    if metadata.license:
        rv.append(Annotation(v.has_license, _reference_or_anyuri(converter, str(metadata.license))))
    if metadata.comment:
        rv.append(Annotation(v.has_comment, LiteralBox(metadata.comment)))
    for source_url in metadata.source or []:
        rv.append(Annotation(v.has_source, _reference_or_anyuri(converter, str(source_url))))
    for see_also_url in metadata.see_also or []:
        rv.append(Annotation(v.see_also, _reference_or_anyuri(converter, str(see_also_url))))
    for creator in metadata.creators or []:
        rv.append(Annotation(v.has_creator, creator))
    return rv


def _reference_or_anyuri(converter: curies.Converter, value: str) -> rdflib.Literal | Reference:
    if license_reference := converter.parse_uri(value):
        return license_reference.to_pydantic()
    else:
        return rdflib.Literal(value, datatype=XSD.anyURI)


def get_owl_bridge_axioms(
    mappings: Iterable[SemanticMapping],
    converter: curies.Converter,
    *,
    minimum_confidence: float | None = None,
    mapping_annotations: bool = False,
    not_implies_disjoint: bool = False,
    declarations: bool = False,
    allow_arbitrary: bool = False,
    mechanism: Mechanism | None = None,
) -> Iterable[Box]:
    """Iterate over OWL bridge axioms from semantic mappings.

    :param mappings: An iterable of semantic mappings
    :param converter: A converter
    :param minimum_confidence: minimum confidence level to keep for exporting bridge
        axioms
    :param mapping_annotations: whether annotations should be added to bridge axioms,
        defaults to false
    :param declarations: whether to include declarations for subject and object entities
    :param not_implies_disjoint: Whether to assume that the curation of a negative exact
        match or equivalence mapping should be used to imply a disjointness axiom.

        .. warning::

            This can be problematic if a negative mapping is trivial, i.e., there exists
            another mapping with a difference predicate between the same subject and
            object that is true. If ``A not exact match B`` and ``A subClassOf B`` are
            both asserted, then implying a disjointness axiom between A and B will cause
            unsatisfiability. To ensure no such trivial negative mappings exist, first
            invoke :func:`sssom_pydantic.process.remove_trivial_negative` on your
            collection of mappings.


    :yields: An iterable of functional OWL "boxes"
    """
    if minimum_confidence is not None:
        mappings = filter_by_confidence(mappings, minimum_confidence)
    mappings = invert_narrow_matches(mappings, converter=converter)
    authors: set[Reference] = set()

    if mechanism is None or mechanism == "bridge":
        func = partial(
            get_owl_bridge_axiom,
            mapping_annotations=mapping_annotations,
            not_implies_disjoint=not_implies_disjoint,
        )
    elif mechanism == "annotation":
        func = partial(
            get_annotation_axioms, allow_arbitrary=allow_arbitrary
        )
    else:
        raise ValueError(f"Unknown mechanism {mechanism}")

    for m in mappings:
        axiom = func(m, converter)
        if axiom is None:
            continue
        if declarations:
            yield f.Declaration(m.subject, _type_to_declaration_type(m.subject_type, m.predicate))
            yield f.Declaration(m.object, _type_to_declaration_type(m.object_type, m.predicate))
            if m.subject.name is not None:
                yield f.LabelMacro(m.subject, m.subject.name)
            if m.object.name is not None:
                yield f.LabelMacro(m.object, m.object.name)
        if m.authors:
            authors.update(m.authors)
        yield axiom

    if mapping_annotations and authors:
        yield f.Declaration(HUMAN_URI, "Class")
        yield f.LabelMacro(HUMAN_URI, "human")
        for author in sorted(authors):
            yield f.Declaration(author, "NamedIndividual")
            yield f.ClassAssertion(HUMAN_URI, author)
            if author_name := getattr(author, "name", None):
                yield f.LabelMacro(author, author_name)


PREDICATE_TO_DEFAULT_DECLARATION_TYPE: dict[Reference, DeclarationType] = {
    v.exact_match: "Class",
    v.broad_match: "Class",
    v.narrow_match: "Class",
    v.equivalent_class: "Class",
    v.equivalent_property: "ObjectProperty",
    v.subproperty_of: "ObjectProperty",
    v.is_a: "Class",
    v.rdf_type: "NamedIndividual",
    v.same_as: "NamedIndividual",
    v.owl_different_from: "NamedIndividual",
    v.owl_disjoint_with: "Class",
    v.owl_complement_of: "Class",
    v.owl_inverse_of: "ObjectProperty",
    v.owl_property_disjoint_with: "ObjectProperty",
}

# see https://mapping-commons.github.io/sssom/dev/EntityTypeEnum/
SIDE_TYPE_REFERENCE_TO_DECLARATION_TYPE: dict[Reference, DeclarationType] = {
    v.owl_class: "Class",
    v.owl_object_property: "ObjectProperty",
    v.owl_data_property: "DataProperty",
    v.owl_annotation_property: "AnnotationProperty",
    v.owl_named_individual: "NamedIndividual",
    v.rdfs_datatype: "Datatype",
    v.rdfs_class: "Class",
    # the following are not perfect, but usually good enough
    v.skos_concept: "Class",
    v.rdfs_resource: "Class",
    v.rdfs_property: "ObjectProperty",
    # the following don't have obvious mappings
    # v.rdfs_literal,
    # v.composed_entity_expression,
}


def _type_to_declaration_type(
    type_reference: Reference | None, predicate: Reference
) -> DeclarationType:
    if type_reference is None:
        return PREDICATE_TO_DEFAULT_DECLARATION_TYPE.get(predicate, "Class")
    return SIDE_TYPE_REFERENCE_TO_DECLARATION_TYPE.get(type_reference, "Class")


def get_owl_bridge_axiom(
    m: SemanticMapping,
    converter: curies.Converter,
    *,
    mapping_annotations: bool = False,
    not_implies_disjoint: bool = False,
) -> Axiom | None:
    """Get an OWL bridge axiom from a semantic mapping.

    :param m: A semantic mapping
    :param converter: A converter
    :param mapping_annotations: Whether to include SSSOM metadata as annotations on the
        produced axioms
    :param not_implies_disjoint: Whether to assume that the curation of a negative exact
        match or equivalence mapping should be used to imply a disjointness axiom.

        .. warning::

            This can be problematic if a negative mapping is trivial, i.e., there exists
            another mapping with a difference predicate between the same subject and
            object that is true. If ``A not exact match B`` and ``A subClassOf B`` are
            both asserted, then implying a disjointness axiom between A and B will cause
            unsatisfiability. To ensure no such trivial negative mappings exist, first
            invoke :func:`sssom_pydantic.process.remove_trivial_negative` on your
            collection of mappings.


    :returns: An OWL axiom, if one can be constructed.
    """
    anns = get_mapping_annotations(m, converter) if mapping_annotations else None
    if m.predicate_modifier is None:
        logical_axiom = _to_logical_axiom(m, anns)
        if logical_axiom is not None:
            return logical_axiom
        return _bridge_annotation(m, anns)
    elif not_implies_disjoint:
        return _handle_logical_not(m, anns=anns)
    return None


def _is_class(r: curies.Reference | None) -> bool:
    return r is None or r == v.owl_class or r == v.skos_concept


def get_mapping_annotations(
    mapping: SemanticMapping, converter: curies.Converter
) -> list[Annotation]:
    """Get annotations from a semantic mapping."""
    return list(_iter_annotations(mapping, converter))


def _iter_annotations(
    mapping: SemanticMapping, converter: curies.Converter
) -> Iterable[Annotation]:
    yield Annotation("sssom:mapping_justification", mapping.justification)
    for author in mapping.authors or []:
        yield Annotation("pav:authoredBy", author)
    if mapping.confidence is not None:
        yield Annotation("sssom:confidence", f.LiteralBox(mapping.confidence))
    if mapping.mapping_tool is not None:
        pass
    if mapping.license is not None:
        yield Annotation(v.has_license, _reference_or_anyuri(converter, mapping.license))
    for creator in mapping.creators or []:
        yield Annotation(v.has_creator, creator)
    for reviewer in mapping.reviewers or []:
        yield Annotation("sssom:reviewer_id", reviewer)
    if mapping.mapping_date is not None:
        yield Annotation("dcterms:created", mapping.mapping_date)
    if mapping.publication_date:
        yield Annotation("dcterms:issued", mapping.publication_date)
    if mapping.comment:
        yield Annotation(v.has_comment, f.LiteralBox(mapping.comment))
    for see_also_uri in mapping.see_also or []:
        yield Annotation(v.see_also, _reference_or_anyuri(converter, see_also_uri))
    # TODO remaining


def _handle_logical_not(m: SemanticMapping, anns: list[Annotation] | None = None) -> Axiom | None:
    match m.predicate:
        case v.exact_match:
            if _is_class(m.subject_type):
                return DisjointClasses([m.subject, m.object], annotations=anns)
            elif m.subject_type == v.owl_named_individual:
                return DifferentIndividuals([m.subject, m.object], annotations=anns)
            elif m.subject_type == v.owl_object_property:
                return DisjointObjectProperties([m.subject, m.object], annotations=anns)
            elif m.subject_type == v.owl_data_property:
                return DisjointDataProperties([m.subject, m.object], annotations=anns)
            # note, there's no concept of DisjointAnnotationProperties since
            # these aren't used for logical axioms
            else:
                return None
        case v.equivalent_class:
            return DisjointClasses([m.subject, m.object], annotations=anns)
        case v.same_as:
            return DifferentIndividuals([m.subject, m.object], annotations=anns)
        case v.equivalent_property:
            if m.subject_type is None or m.subject_type == v.owl_object_property:
                return DisjointObjectProperties([m.subject, m.object], annotations=anns)
            elif m.subject_type == v.owl_data_property:
                return DisjointDataProperties([m.subject, m.object], annotations=anns)
            # note, there's no concept of DisjointAnnotationProperties since
            # these aren't used for logical axioms
            else:
                return None
    return None


def _bridge_annotation(m: SemanticMapping, anns: list[Annotation] | None = None) -> Axiom | None:
    match m.predicate:
        case v.exact_match:
            if _is_class(m.subject_type):
                return EquivalentClasses([m.subject, m.object], annotations=anns)
            elif m.subject_type == v.owl_named_individual:
                return SameIndividual([m.subject, m.object], annotations=anns)
            elif m.subject_type == v.owl_object_property:
                return EquivalentObjectProperties([m.subject, m.object], annotations=anns)
            elif m.subject_type == v.owl_data_property:
                return EquivalentDataProperties([m.subject, m.object], annotations=anns)
            # note, there's no concept of EquivalentAnnotationProperties since
            # these aren't used for logical axioms
            else:
                return None
        case v.broad_match:
            if _is_class(m.subject_type):
                return SubClassOf(m.subject, m.object, annotations=anns)
            elif m.subject_type == v.owl_named_individual and _is_class(m.object_type):
                return ClassAssertion(m.object, m.subject, annotations=anns)
            elif m.subject_type == v.owl_object_property:
                return SubObjectPropertyOf(m.subject, m.object, annotations=anns)
            elif m.subject_type == v.owl_data_property:
                return SubDataPropertyOf(m.subject, m.object, annotations=anns)
            elif m.subject_type == v.owl_annotation_property:
                return SubAnnotationPropertyOf(m.subject, m.object, annotations=anns)
            else:
                return None
        # narrow match - excluded because inversion should be done before
        # close match, related match, see also, etc. - excluded because not logical
    return None


def _to_logical_axiom(m: SemanticMapping, anns: list[Annotation] | None = None) -> Axiom | None:
    match m.predicate:
        case v.is_a:
            return SubClassOf(m.subject, m.object, annotations=anns)
        case v.rdf_type:
            return ClassAssertion(m.object, m.subject, annotations=anns)
        case v.subproperty_of:
            if m.subject_type is None or m.subject_type == v.owl_object_property:
                return SubObjectPropertyOf(m.subject, m.object, annotations=anns)
            elif m.subject_type == v.owl_data_property:
                return SubDataPropertyOf(m.subject, m.object, annotations=anns)
            elif m.subject_type == v.owl_annotation_property:
                return SubAnnotationPropertyOf(m.subject, m.object, annotations=anns)
        case v.equivalent_class:
            return EquivalentClasses([m.subject, m.object], annotations=anns)
        case v.same_as:
            return SameIndividual([m.subject, m.object], annotations=anns)
        case v.equivalent_property:
            if m.subject_type is None or m.subject_type == v.owl_object_property:
                return EquivalentObjectProperties([m.subject, m.object], annotations=anns)
            elif m.subject_type == v.owl_data_property:
                return EquivalentDataProperties([m.subject, m.object], annotations=anns)
            # note, there's no concept of EquivalentAnnotationProperties since
            # these aren't used for logical axioms
            else:
                return None

        case v.owl_complement_of:
            raise NotImplementedError(
                "complement of predicate not implemented. Requires creating a more complex "
                "class macro upstream in funowl"
            )
        case v.owl_different_from:
            return DifferentIndividuals([m.subject, m.object], annotations=anns)
        case v.owl_disjoint_with:
            return DisjointClasses([m.subject, m.object], annotations=anns)
        case v.owl_inverse_of:
            return InverseObjectProperties(m.subject, m.object, annotations=anns)
        case v.owl_property_disjoint_with:
            if m.subject_type is None or m.subject_type == v.owl_object_property:
                return DisjointObjectProperties([m.subject, m.object], annotations=anns)
            elif m.subject_type == v.owl_data_property:
                return DisjointDataProperties([m.subject, m.object], annotations=anns)
            else:
                return None
    return None


def get_annotation_axioms(
    m: SemanticMapping,
    converter: curies.Converter,
    *,
    allow_arbitrary: bool = False
) -> Axiom | None:
    """Get an OWL bridge axiom from a semantic mapping."""
    anns = get_mapping_annotations(m, converter=converter)
    if m.predicate_modifier is not None:
        anns.append(Annotation("sssom:predicate_modifier", f.LiteralBox("Not")))
    if m.predicate_modifier is None and (rv := _to_logical_axiom(m, anns)):
        return rv
    if m.predicate not in v.extended_match_typedefs and not allow_arbitrary:
        logger.warning("skipping unsupported predicate %s", m.predicate)
        return None
    return AnnotationAssertion(m.predicate, m.subject, m.object, annotations=anns)
